name: Android Kernel Build

on:
  workflow_dispatch:    # Allows manual triggering from GitHub
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      
    - name: Set up Clang
      run: |
        git clone --depth=1 https://gitlab.com/ElectroPerf/atom-x-clang.git
        export PATH="$(pwd)/atom-x-clang/bin:$PATH"

    - name: Set up necessary repositories
      run: |
        git clone --depth=1 https://github.com/Atom-X-Devs/android_device_xiaomi_sm7325.git device/xiaomi/sm7325
        git clone --depth=1 https://github.com/Atom-X-Devs/android_vendor_xiaomi.git vendor/xiaomi

    - name: Configure Environment
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export KBUILD_OUTPUT=$(pwd)/out

    - name: Build Kernel
      run: |
        make O=$KBUILD_OUTPUT xtended_defconfig
        make O=$KBUILD_OUTPUT -j$(nproc)
    
    - name: Upload Kernel
      uses: actions/upload-artifact@v2
      with:
        name: kernel
        path: ${{ github.workspace }}/out/arch/arm64/boot/Image.gz-dtb
