name: Kernel Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kernel repository
        uses: actions/checkout@v2
        with:
          repository: qa1729/android_kernel_xiaomi_sm7325
          path: android_kernel_xiaomi_sm7325

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget curl clang flex bison libssl-dev libelf-dev

      - name: Clone dependencies
        run: |
          if [ ! -d "scripts" ]; then
            git clone https://github.com/Atom-X-Devs/scripts.git
          fi
          if [ ! -d "AnyKernel3" ]; then
            git clone https://github.com/Atom-X-Devs/AnyKernel3.git
          fi
          if [ ! -d "atom-x-clang" ]; then
            git clone https://gitlab.com/ElectroPerf/atom-x-clang.git
          fi

      - name: Configure Kernel
        run: |
          cd android_kernel_xiaomi_sm7325
          if [ -f "kconfig" ]; then
            cp kconfig .config  # Copy kconfig to .config
          elif [ -f "Makefile" ]; then
            make [defconfig]  # Replace [defconfig] with your actual defconfig
          else
            echo "No valid configuration file found!"
            exit 1
          fi

      - name: Build Kernel
        run: |
          cd android_kernel_xiaomi_sm7325
          export ARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=aarch64-linux-androidkernel-
          export CROSS_COMPILE_COMPAT=arm-linux-androideabi-
          export LINUX_GCC_CROSS_COMPILE_PREBUILTS_BIN=prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin
          export LINUX_GCC_CROSS_COMPILE_ARM32_PREBUILTS_BIN=prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/
          export CC=../atom-x-clang/bin/clang  # Adjust path if necessary
          make -j$(nproc) O=out

      - name: Package Kernel
        run: |
          cd android_kernel_xiaomi_sm7325/out
          zip -r ../kernel.zip *

      - name: Upload Kernel
        uses: actions/upload-artifact@v3
        with:
          name: kernel
          path: kernel.zip
